name: Update GitHub Snake

on:
  push:
    branches:
      - main
      - output

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # importante para pegar todos os commits

      - name: Run GitHub Snake Action
        uses: dkhamsing/github-snake-action@v1

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git checkout output || git checkout -b output
          git add dist/github-snake-dark.svg
          git commit -m "Update snake animation [skip ci]" || echo "No changes to commit"
          git push origin output
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
